version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - ./db/:/data/db
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env.prod
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - .:/app
      - /app/shopping/node_modules
    env_file:
      - ./shopping/.env.prod
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongo"

    volumes:
      - .:/app/
      - /app/customer/node_modules
    env_file:
      - ./customer/.env.prod
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - "80:80"